name: owl
channels:
- conda-forge
- defaults
dependencies:
- pip
- python>=3.10,<3.13
- pywps>=4.5.2,<4.7
- jinja2
- click
- psutil
# tests
- pytest
# data fetch
# - cdsapi
# visualisation
- matplotlib
- cartopy
# data analysis
- netCDF4
- joblib
- xarray
- scipy
- scikit-learn
# - python-cdo
# - cdo # avoidable if possible
